### ISSUE TITLE
Getting KeyError: u'CollectionType' in remote.py

### ISSUE THREAD

**Issue by senoadiw** [mcarlton00/mopidy-jellyfin#5]
Hi,

Here are my version details:

* Jellyfin 10.3.7
* Mopidy 2.2.3
* Mopidy-Jellyfin 0.5.3

my mopidy.conf

```
[jellyfin]
enabled = true
hostname = 192.168.1.x
port = 8096
username = admin
password = password
libraries = Music
```

I can play music files just fine from the Music library via Jellyfin web. However in M.A.L.P. nothing shows up upon clicking Files > Jellyfin

Restarting the mopidy service I can see in Active Devices on Jellyfin dashboard the admin user logging in via Mopidy-Jellyfin.

Checking the service log with journalctl -u mopidy show the following error:

```
Aug 14 18:16:41 qtpi mopidy[30943]:   File "/usr/local/lib/python2.7/dist-packages/mopidy_jellyfin/remote.py", line 243, in get_music_root
Aug 14 18:16:41 qtpi mopidy[30943]:     if library['CollectionType'] == 'music'
Aug 14 18:16:41 qtpi mopidy[30943]: KeyError: u'CollectionType'
```

Cheers

**Comment by mcarlton00** [comment]
I've noticed some occasional weirdness in M.A.L.P. where once you get into an artist/album it shows as empty. If you touch the 3 dots in the upper left corner and choose "Show all tracks", they should start showing up in the that folder.  I haven't had time to track down if it's a mopidy-jellyfin issue or a M.A.L.P. issue.

I'll have to look into the KeyError sometime in the next few days.

**Comment by mcarlton00** [comment]
Sorry for the huge delay, I've been working on the Kodi addon a lot lately.  With the new release I just pushed out yesterday it should fix the KeyError messages in the logs.  If you keep having issues then it's something else we'll have to track down, but closing for now since the primary issue is fixed.
