### ISSUE TITLE
https://github.com/mcarlton00/mopidy-jellyfin.git

### ISSUE THREAD

**Issue by accad** [mcarlton00/mopidy-jellyfin#6]
This must be something very basic, but for the life of me I cannot figure it out

Full error:

RROR    2019-11-01 11:38:28,144 [3490:MainThread] mopidy.commands
  Got un-handled exception from JellyfinBackend
Traceback (most recent call last):
  File "/home/mopidy-srv/.local/lib/python2.7/site-packages/mopidy/commands.py", line 237, in _actor_error_handling
    yield
  File "/home/mopidy-srv/.local/lib/python2.7/site-packages/mopidy/commands.py", line 386, in start_backends
    config=config, audio=audio).proxy()
  File "/home/mopidy-srv/.local/lib/python2.7/site-packages/pykka/_actor.py", line 91, in start
    obj = cls(*args, **kwargs)
  File "/home/mopidy-srv/.local/lib/python2.7/site-packages/mopidy_jellyfin/backend.py", line 26, in __init__
    self.remote = JellyfinHandler(config)
  File "/home/mopidy-srv/.local/lib/python2.7/site-packages/mopidy_jellyfin/remote.py", line 44, in __init__
    self.user_id = self.user_id or self._get_user()[0].get('Id')
  File "/home/mopidy-srv/.local/lib/python2.7/site-packages/mopidy_jellyfin/remote.py", line 60, in _get_user
    raise Exception('No Jellyfin user {} found'.format(self.username))
Exception: No Jellyfin user 'user' found

Relevant config:

[jellyfin]
enabled = true
username = 'user'
user_id = 
password = ********
hostname = 192.168.72.3
libraries = 
port = 8096
client_cert = 
client_key =

I tried with and without the quotes for the username and the password, I know the user exists, I tried also with admin, it just refuses to authenticate

Not sure what I am doing wrong, or where I should look at this point

Python 2.7.17
Mopidy 2.3.1
Jellyfin version: 10.4.0

**Comment by accad** [comment]
Like I said. it was simple

Reading remote.py, the user has to be visible in <hostname>/Users
I was checking "Hide user from login screen", unchecking this made it work

Thank you

**Comment by mcarlton00** [comment]
I believe you have to use `user_id` instead of `user` if you have a hidden account, but I haven't tested that explicitly yet.  That can probably be improved, either in the code itself or just with better instructions

**Comment by accad** [comment]
You are correct, I just stopped reading after I found the /Users/Public lookup

Tested by adding the user_id to the config and can now login with hidden user

Suggest we add that to the README or as a configuration hint.

Now how to find the ID of the users from Jellyfin interface :)

**Comment by mcarlton00** [comment]
If you haven't already figured it out, I've updated the readme with better instructions for adding a hidden user and how to find the `user_id` value for your user
